### ISSUE TITLE
Exception in last PhpStorm 2018.2 EAP build

### ISSUE THREAD

**Issue by pahan35** [Haehnchen/idea-php-laravel-plugin#188]
After updating to 2018.2 EAP Build #PS-182.3208.33 I noticed that there appears an exception error message in IDE errors section

```
java.lang.NoClassDefFoundError: Could not initialize class de.espend.idea.laravel.LaravelIcons
	at de.espend.idea.laravel.blade.TemplateLineMarker.lambda$visitOverwrittenTemplateFile$2(TemplateLineMarker.java:291)
	at de.espend.idea.laravel.blade.util.BladeTemplateUtil$DirectivePsiRecursiveElementWalkingVisitor.visitElement(BladeTemplateUtil.java:282)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at de.espend.idea.laravel.blade.util.BladeTemplateUtil$DirectivePsiRecursiveElementWalkingVisitor.visitElement(BladeTemplateUtil.java:288)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:728)
	at de.espend.idea.laravel.blade.util.BladeTemplateUtil.visitYield(BladeTemplateUtil.java:160)
	at de.espend.idea.laravel.blade.TemplateLineMarker.visitOverwrittenTemplateFile(TemplateLineMarker.java:296)
	at de.espend.idea.laravel.blade.TemplateLineMarker.visitOverwrittenTemplateFile(TemplateLineMarker.java:280)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectOverwrittenSection(TemplateLineMarker.java:170)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectSlowLineMarkers(TemplateLineMarker.java:84)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:197)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

[idea-laravel-plugin.log](https://github.com/Haehnchen/idea-php-laravel-plugin/files/2101637/idea-laravel-plugin.log)

**Comment by Kurre** [comment]
This seems to be related to the issue at IntelliJ's end: https://youtrack.jetbrains.com/issue/WI-42534 (?)

It seems that this commit broke it: https://github.com/JetBrains/intellij-community/commit/416b77b71fa6942101deb41ac78741cec4b2391d

There are some commits after this, which apparently should fix this: https://github.com/JetBrains/intellij-community/commits/master/platform/util/src/com/intellij/openapi/util/IconLoader.java

**Comment by pahan35** [comment]
@Kurre thank you for your investigation!

Looks like it can be closed. Will be waiting for new EAP to try is it fixed or not.
